-- ### Jinja renders BEFORE DCM evaluates this file
--
-- Three ideas and no more: one loop over the manifest's `teams` list, one
-- dictionary value injected into a real object property, one macro call.
-- Read the rendered copy of this file in the PLAN output to see the SQL DCM
-- actually evaluated.
{% for team in teams %}
    {% set team_name = team.name | upper %}

    DEFINE SCHEMA DCM_DEMO_1{{env_suffix}}.{{team_name}}
        COMMENT = 'Team schema generated by the Jinja loop'
        DATA_RETENTION_TIME_IN_DAYS = {{ team.data_retention_days }};

    {{ create_team_roles(team_name) }}

{% endfor %}
