select
	MENU.MENU_ITEM_ID,
	MENU.MENU_ITEM_NAME,
	sum(DETAIL.QUANTITY) as QUANTITY_SOLD,
	sum(DETAIL.QUANTITY * MENU.SALE_PRICE_USD) as REVENUE
from
	{{ source('RAW', 'MENU') }} as MENU
join
	{{ source('RAW', 'ORDER_DETAIL') }} as DETAIL
	on MENU.MENU_ITEM_ID = DETAIL.MENU_ITEM_ID
group by
	MENU.MENU_ITEM_ID,
	MENU.MENU_ITEM_NAME