define semantic view DCM_DEMO_1{{env_suffix}}.SERVE.ORDERS_SEMANTIC_VIEW
	tables (
		ORDERS as DCM_DEMO_1{{env_suffix}}.ANALYTICS.ENRICHED_ORDER_DETAILS
	)
	dimensions (
		ORDERS.ORDER_TIMESTAMP as ORDERS.ORDER_TS,
		ORDERS.MENU_ITEM_NAME as ORDERS.MENU_ITEM_NAME,
		ORDERS.ITEM_CATEGORY as ORDERS.ITEM_CATEGORY,
		ORDERS.CUSTOMER_CITY as ORDERS.CUSTOMER_CITY,
		ORDERS.TRUCK_BRAND_NAME as ORDERS.TRUCK_BRAND_NAME
	)
	metrics (
		ORDERS.TOTAL_REVENUE as sum(ORDERS.LINE_ITEM_REVENUE),
		ORDERS.TOTAL_PROFIT as sum(ORDERS.LINE_ITEM_PROFIT),
		ORDERS.ORDER_COUNT as count(distinct ORDERS.ORDER_ID),
		ORDERS.TOTAL_QUANTITY_SOLD as sum(ORDERS.QUANTITY)
	)
	comment = 'Order-line measures; order count counts distinct order identifiers'
;