DEFINE SCHEMA DCM_DEMO_3{{env_suffix}}.ANALYTICS;

DEFINE DYNAMIC TABLE DCM_DEMO_3{{env_suffix}}.ANALYTICS.ENRICHED_ORDER_DETAILS
WAREHOUSE = DCM_DEMO_3_WH{{env_suffix}}
TARGET_LAG = 'DOWNSTREAM'
INITIALIZE = 'ON_SCHEDULE'
DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES'
AS
SELECT
    oh.ORDER_ID,
    oh.ORDER_TS,
    od.QUANTITY,
    m.MENU_ITEM_NAME,
    m.ITEM_CATEGORY,
    m.SALE_PRICE_USD,
    m.COST_OF_GOODS_USD,
    (od.QUANTITY * m.SALE_PRICE_USD) AS LINE_ITEM_REVENUE,
    (od.QUANTITY * (m.SALE_PRICE_USD - m.COST_OF_GOODS_USD)) AS LINE_ITEM_PROFIT,
    c.CUSTOMER_ID,
    c.FIRST_NAME,
    c.LAST_NAME,
    INITCAP(c.CITY) AS CUSTOMER_CITY,
    t.TRUCK_ID,
    t.TRUCK_BRAND_NAME
FROM DCM_DEMO_3{{env_suffix}}.RAW.ORDER_HEADER oh
JOIN DCM_DEMO_3{{env_suffix}}.RAW.ORDER_DETAIL od ON oh.ORDER_ID = od.ORDER_ID
JOIN DCM_DEMO_3{{env_suffix}}.RAW.MENU m ON od.MENU_ITEM_ID = m.MENU_ITEM_ID
JOIN DCM_DEMO_3{{env_suffix}}.RAW.CUSTOMER c ON oh.CUSTOMER_ID = c.CUSTOMER_ID
JOIN DCM_DEMO_3{{env_suffix}}.RAW.TRUCK t ON oh.TRUCK_ID = t.TRUCK_ID;

DEFINE DYNAMIC TABLE DCM_DEMO_3{{env_suffix}}.ANALYTICS.MENU_ITEM_POPULARITY
WAREHOUSE = DCM_DEMO_3_WH{{env_suffix}}
TARGET_LAG = '1 day'
INITIALIZE = 'ON_SCHEDULE'
DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES'
AS
SELECT
    MENU_ITEM_NAME,
    ITEM_CATEGORY,
    COUNT(DISTINCT ORDER_ID) AS NUMBER_OF_ORDERS,
    SUM(QUANTITY) AS TOTAL_QUANTITY_SOLD,
    SUM(LINE_ITEM_REVENUE) AS TOTAL_REVENUE
FROM DCM_DEMO_3{{env_suffix}}.ANALYTICS.ENRICHED_ORDER_DETAILS
GROUP BY MENU_ITEM_NAME, ITEM_CATEGORY
ORDER BY TOTAL_REVENUE DESC;

DEFINE DYNAMIC TABLE DCM_DEMO_3{{env_suffix}}.ANALYTICS.CUSTOMER_SPENDING_SUMMARY
WAREHOUSE = DCM_DEMO_3_WH{{env_suffix}}
TARGET_LAG = '2 days'
INITIALIZE = 'ON_SCHEDULE'
AS
SELECT
    CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    CUSTOMER_CITY,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    SUM(LINE_ITEM_REVENUE) AS TOTAL_SPEND_USD,
    MIN(ORDER_TS) AS FIRST_ORDER_DATE,
    MAX(ORDER_TS) AS LATEST_ORDER_DATE
FROM DCM_DEMO_3{{env_suffix}}.ANALYTICS.ENRICHED_ORDER_DETAILS
GROUP BY CUSTOMER_ID, FIRST_NAME, LAST_NAME, CUSTOMER_CITY
ORDER BY TOTAL_SPEND_USD DESC;

DEFINE DYNAMIC TABLE DCM_DEMO_3{{env_suffix}}.ANALYTICS.TRUCK_PERFORMANCE
WAREHOUSE = DCM_DEMO_3_WH{{env_suffix}}
TARGET_LAG = '12 hours'
INITIALIZE = 'ON_SCHEDULE'
AS
SELECT
    TRUCK_BRAND_NAME,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    SUM(LINE_ITEM_REVENUE) AS TOTAL_REVENUE,
    SUM(LINE_ITEM_PROFIT) AS TOTAL_PROFIT,
    DCM_DEMO_3{{env_suffix}}.ANALYTICS.CALCULATE_PROFIT_MARGIN(
        SUM(LINE_ITEM_REVENUE),
        SUM(LINE_ITEM_REVENUE) - SUM(LINE_ITEM_PROFIT)
    ) AS PROFIT_MARGIN_PCT
FROM DCM_DEMO_3{{env_suffix}}.ANALYTICS.ENRICHED_ORDER_DETAILS
GROUP BY TRUCK_BRAND_NAME
ORDER BY TOTAL_REVENUE DESC;

DEFINE FUNCTION DCM_DEMO_3{{env_suffix}}.ANALYTICS.CALCULATE_PROFIT_MARGIN(REVENUE NUMBER, COST NUMBER)
RETURNS NUMBER(10,2)
AS
$$
    CASE WHEN REVENUE = 0
        THEN 0
        ELSE ROUND(((REVENUE - COST) / REVENUE) * 100, 2)
    END
$$;
