DEFINE STAGE DCM_DEMO_3{{env_suffix}}.RAW.TASTY_BYTES_ORDERS_STAGE
    COMMENT = 'Internal stage for daily incoming Tasty Bytes order files (CSV)';

DEFINE TABLE DCM_DEMO_3{{env_suffix}}.RAW.DAILY_ORDERS_INCOMING (
    ORDER_ID NUMBER,
    CUSTOMER_ID NUMBER,
    TRUCK_ID NUMBER,
    ORDER_TS TIMESTAMP_NTZ,
    MENU_ITEM_ID NUMBER,
    QUANTITY NUMBER
)
CHANGE_TRACKING = TRUE;

DEFINE TASK DCM_DEMO_3{{env_suffix}}.ANALYTICS.TSK_INGEST_DAILY_ORDERS
    WAREHOUSE = 'DCM_DEMO_3_WH{{env_suffix}}'
    SCHEDULE = 'USING CRON 0 5 * * * UTC'
AS
BEGIN
    COPY INTO DCM_DEMO_3{{env_suffix}}.RAW.DAILY_ORDERS_INCOMING
    FROM @DCM_DEMO_3{{env_suffix}}.RAW.TASTY_BYTES_ORDERS_STAGE
    FILE_FORMAT = (
        TYPE = 'CSV',
        FIELD_DELIMITER = ',',
        SKIP_HEADER = 1,
        NULL_IF = ('NULL', 'null'),
        EMPTY_FIELD_AS_NULL = TRUE,
        FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    )
    ON_ERROR = 'CONTINUE';

    INSERT INTO DCM_DEMO_3{{env_suffix}}.RAW.ORDER_HEADER (ORDER_ID, CUSTOMER_ID, TRUCK_ID, ORDER_TS)
    SELECT DISTINCT ORDER_ID, CUSTOMER_ID, TRUCK_ID, ORDER_TS
    FROM DCM_DEMO_3{{env_suffix}}.RAW.DAILY_ORDERS_INCOMING src
    WHERE NOT EXISTS (
        SELECT 1
        FROM DCM_DEMO_3{{env_suffix}}.RAW.ORDER_HEADER dest
        WHERE dest.ORDER_ID = src.ORDER_ID
    );

    INSERT INTO DCM_DEMO_3{{env_suffix}}.RAW.ORDER_DETAIL (ORDER_ID, MENU_ITEM_ID, QUANTITY)
    SELECT ORDER_ID, MENU_ITEM_ID, QUANTITY
    FROM DCM_DEMO_3{{env_suffix}}.RAW.DAILY_ORDERS_INCOMING;

    TRUNCATE TABLE DCM_DEMO_3{{env_suffix}}.RAW.DAILY_ORDERS_INCOMING;

    REMOVE @DCM_DEMO_3{{env_suffix}}.RAW.TASTY_BYTES_ORDERS_STAGE PATTERN='.*.csv';
END;
