DEFINE DATABASE DCM_DEMO_3{{env_suffix}}
    COMMENT = 'This is a Quickstart Demo for DCM Projects with Dynamic Tables';

DEFINE SCHEMA DCM_DEMO_3{{env_suffix}}.RAW
    COMMENT = 'For Task copying sample data into landing tables';

DEFINE TABLE DCM_DEMO_3{{env_suffix}}.RAW.ALL_ITEMS(
    ITEM_NAME VARCHAR,
    ITEM_ID VARCHAR,
    ITEM_CATEGORY ARRAY
)
CHANGE_TRACKING = TRUE;

DEFINE TABLE DCM_DEMO_3{{env_suffix}}.RAW.ALL_REGIONS(
    REGION VARCHAR,
    REGION_ID NUMBER,
    COUNTRY VARCHAR,
    CATEGORIES ARRAY,
    ONLINE BOOLEAN
)
CHANGE_TRACKING = TRUE;

DEFINE TABLE DCM_DEMO_3{{env_suffix}}.RAW.INVENTORY(
    ITEM_ID NUMBER,
    REGION_ID NUMBER,
    IN_STOCK NUMBER,
    COUNTED_ON DATE
)
CHANGE_TRACKING = TRUE
DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES';

DEFINE TABLE DCM_DEMO_3{{env_suffix}}.RAW.MENU (
    MENU_ITEM_ID NUMBER,
    MENU_ITEM_NAME VARCHAR,
    ITEM_CATEGORY VARCHAR,
    COST_OF_GOODS_USD NUMBER(10, 2),
    SALE_PRICE_USD NUMBER(10, 2)
)
CHANGE_TRACKING = TRUE;

DEFINE TABLE DCM_DEMO_3{{env_suffix}}.RAW.TRUCK (
    TRUCK_ID NUMBER,
    TRUCK_BRAND_NAME VARCHAR,
    MENU_TYPE VARCHAR
)
CHANGE_TRACKING = TRUE;

DEFINE TABLE DCM_DEMO_3{{env_suffix}}.RAW.CUSTOMER (
    CUSTOMER_ID NUMBER,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    CITY VARCHAR
)
CHANGE_TRACKING = TRUE;

DEFINE TABLE DCM_DEMO_3{{env_suffix}}.RAW.ORDER_HEADER (
    ORDER_ID NUMBER,
    CUSTOMER_ID NUMBER,
    TRUCK_ID NUMBER,
    ORDER_TS TIMESTAMP_NTZ
)
CHANGE_TRACKING = TRUE;

DEFINE TABLE DCM_DEMO_3{{env_suffix}}.RAW.ORDER_DETAIL (
    ORDER_ID NUMBER,
    MENU_ITEM_ID NUMBER,
    QUANTITY NUMBER
)
CHANGE_TRACKING = TRUE;
