DEFINE SCHEMA DCM_DEMO_3{{env_suffix}}.SERVE;

DEFINE VIEW DCM_DEMO_3{{env_suffix}}.SERVE.V_DASHBOARD_DAILY_SALES
DATA_METRIC_SCHEDULE = 'USING CRON 0 8 * * * UTC'
AS
SELECT
    DATE_TRUNC('DAY', ORDER_TS) AS SALE_DATE,
    COUNT(DISTINCT ORDER_ID) AS DAILY_ORDERS,
    SUM(LINE_ITEM_REVENUE) AS DAILY_REVENUE,
    SUM(LINE_ITEM_PROFIT) AS DAILY_PROFITS
FROM DCM_DEMO_3{{env_suffix}}.ANALYTICS.ENRICHED_ORDER_DETAILS
GROUP BY SALE_DATE
ORDER BY SALE_DATE;

DEFINE VIEW DCM_DEMO_3{{env_suffix}}.SERVE.V_DASHBOARD_KPI_SUMMARY
DATA_METRIC_SCHEDULE = 'USING CRON 0 8 * * * UTC'
AS
SELECT
    SUM(TOTAL_SPEND_USD) AS TOTAL_LIFETIME_REVENUE,
    COUNT(DISTINCT CUSTOMER_ID) AS TOTAL_CUSTOMERS,
    SUM(TOTAL_ORDERS) AS TOTAL_ORDERS,
    SUM(TOTAL_SPEND_USD) / SUM(TOTAL_ORDERS) AS AVERAGE_ORDER_VALUE
FROM DCM_DEMO_3{{env_suffix}}.ANALYTICS.CUSTOMER_SPENDING_SUMMARY;

DEFINE VIEW DCM_DEMO_3{{env_suffix}}.SERVE.V_DASHBOARD_SALES_BY_CATEGORY_CITY
DATA_METRIC_SCHEDULE = 'USING CRON 0 4 * * * UTC'
AS
SELECT
    ITEM_CATEGORY,
    CUSTOMER_CITY,
    SUM(LINE_ITEM_REVENUE) AS TOTAL_REVENUE
FROM DCM_DEMO_3{{env_suffix}}.ANALYTICS.ENRICHED_ORDER_DETAILS
GROUP BY ITEM_CATEGORY, CUSTOMER_CITY
ORDER BY ITEM_CATEGORY, CUSTOMER_CITY;

DEFINE SECURE VIEW DCM_DEMO_3{{env_suffix}}.SERVE.V_DASHBOARD_NEW_VS_RETURNING_CUSTOMERS
DATA_METRIC_SCHEDULE = 'USING CRON 0 8 * * * UTC'
AS
WITH customer_order_dates AS (
    SELECT
        e.ORDER_ID,
        e.CUSTOMER_ID,
        DATE_TRUNC('DAY', e.ORDER_TS) AS ORDER_DATE,
        DATE_TRUNC('DAY', s.FIRST_ORDER_DATE) AS CUSTOMER_FIRST_ORDER_DATE,
        e.LINE_ITEM_REVENUE
    FROM DCM_DEMO_3{{env_suffix}}.ANALYTICS.ENRICHED_ORDER_DETAILS e
    JOIN DCM_DEMO_3{{env_suffix}}.ANALYTICS.CUSTOMER_SPENDING_SUMMARY s
        ON e.CUSTOMER_ID = s.CUSTOMER_ID
)
SELECT
    ORDER_DATE,
    CASE WHEN ORDER_DATE = CUSTOMER_FIRST_ORDER_DATE
        THEN 'New Customer'
        ELSE 'Returning Customer'
    END AS CUSTOMER_TYPE,
    SUM(LINE_ITEM_REVENUE) AS REVENUE
FROM customer_order_dates
GROUP BY ORDER_DATE, CUSTOMER_TYPE
ORDER BY ORDER_DATE DESC, CUSTOMER_TYPE;
